# Generated by Django 3.2 on 2024-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_update_payment_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='totalamount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
