# Generated by Django 3.2 on 2024-08-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orderplaced_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='totalamount',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
