# Generated by Django 3.2 on 2024-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240823_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
