# Generated by Django 3.2 on 2024-08-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
