# Generated by Django 3.2 on 2024-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240823_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('PH', 'Phone'), ('LP', 'Laptop'), ('FE', 'FemaleWear'), ('MW', 'MaleWear'), ('FW', 'FootWear'), ('AC', 'Accessory')], max_length=2),
        ),
    ]
